export const GALLERY_DATA = [
  {
    id: 1,
    title: "Fake PayPal Billing Email",
    caption: "Sophisticated clone using paypa1.com domain with urgent account suspension threat.",
    type: "email",
    status: "phish",
    likes: 47,
    thumb: '📧 PAYPAL BILLING FAKE\n\nFROM: billing@paypa1.com\n"Your account suspended..."',
  },
  {
    id: 2,
    title: "DHL Package Delivery Smish",
    caption: "SMS claiming undeliverable package with bit.ly link leading to credential harvester.",
    type: "sms",
    status: "phish",
    likes: 31,
    thumb: '📱 DHL TRACKING SMS\n\n"Your package held.\nClick: bit.ly/dhl..."',
  },
  {
    id: 3,
    title: "Microsoft 365 Password Reset",
    caption: "Fake Microsoft login page with pixel-perfect copy of the sign-in portal.",
    type: "web",
    status: "review",
    likes: 22,
    thumb: "🌐 MICROSOFT FAKE\n\nmicros0ft-login.net\n[Login form]",
  },
  {
    id: 4,
    title: "IRS Tax Refund Scam Email",
    caption: "Urgent email claiming tax refund available requiring SSN verification.",
    type: "email",
    status: "phish",
    likes: 58,
    thumb: '📧 IRS SCAM EMAIL\n\n"Tax refund of $2,400\nVerify SSN now..."',
  },
  {
    id: 5,
    title: "Netflix Account Suspension",
    caption: "Well-crafted HTML email with Netflix branding asking to update payment.",
    type: "email",
    status: "phish",
    likes: 39,
    thumb: '📧 NETFLIX PHISH\n\n"Your membership\nhas been suspended"',
  },
  {
    id: 6,
    title: "Suspicious WhatsApp Investment",
    caption: "Crypto doubling scam using fake celebrity endorsement and WhatsApp groups.",
    type: "sms",
    status: "dismissed",
    likes: 12,
    thumb: '📱 CRYPTO SCAM\n\n"Double your BTC!\nJoin our group..."',
  },
];
