export const LB_DATA = [
  {
    rank: 1,
    name: "CyberKnight_99",
    initials: "CK",
    color: "linear-gradient(135deg,#ffd600,#f59e0b)",
    xp: 12480,
    level: 42,
    streak: 21,
    badges: ["🏆", "🛡️", "🎯", "⚡", "🔥"],
  },
  {
    rank: 2,
    name: "PhishHunter",
    initials: "PH",
    color: "linear-gradient(135deg,#94a3b8,#64748b)",
    xp: 10920,
    level: 38,
    streak: 14,
    badges: ["🏆", "🛡️", "🎯", "⚡"],
  },
  {
    rank: 3,
    name: "ZeroX_Hacks",
    initials: "ZX",
    color: "linear-gradient(135deg,#cd7f32,#a0522d)",
    xp: 9340,
    level: 31,
    streak: 8,
    badges: ["🏆", "🎯", "⚡"],
  },
  {
    rank: 4,
    name: "NexGuard",
    initials: "NX",
    color: "linear-gradient(135deg,#00f5ff,#0891b2)",
    xp: 7210,
    level: 24,
    streak: 5,
    badges: ["🏆", "🎯"],
  },
  {
    rank: 5,
    name: "SecureRobot",
    initials: "SR",
    color: "linear-gradient(135deg,#00ff9d,#059669)",
    xp: 6550,
    level: 19,
    streak: 3,
    badges: ["🎯"],
  },
  {
    rank: 6,
    name: "DataDefender",
    initials: "DD",
    color: "linear-gradient(135deg,#d500f9,#4f46e5)",
    xp: 5200,
    level: 17,
    streak: 7,
    badges: ["🛡️", "⚡"],
  },
  {
    rank: 7,
    name: "Alice_InfoSec",
    initials: "AI",
    color: "linear-gradient(135deg,#ec4899,#be185d)",
    xp: 4100,
    level: 14,
    streak: 2,
    badges: ["🎯"],
  },
  {
    rank: 8,
    name: "Th3Watcher",
    initials: "TW",
    color: "linear-gradient(135deg,#f59e0b,#d97706)",
    xp: 3850,
    level: 12,
    streak: 4,
    badges: ["🏆"],
  },
  {
    rank: 47,
    name: "You (CyberKnight)",
    initials: "CK",
    color: "linear-gradient(135deg,#00f5ff,#d500f9)",
    xp: 1250,
    level: 8,
    streak: 5,
    badges: ["🎯", "⚡"],
    isYou: true,
  },
];
