export const T = {
  page: {
    background: "#000509",
    minHeight: "100vh",
    color: "#e0f7fa",
    fontFamily: "'Rajdhani', sans-serif",
    position: "relative",
    overflowX: "hidden",
  },
  card: {
    background:
      "linear-gradient(135deg,rgba(0,12,26,0.95) 0%,rgba(0,5,14,0.98) 100%)",
    border: "1px solid rgba(0,245,255,0.12)",
    borderRadius: 6,
    backdropFilter: "blur(24px)",
    position: "relative",
    overflow: "hidden",
    transition: "all .3s",
  },
  logo: {
    fontFamily: "'Orbitron', sans-serif",
    fontWeight: 900,
    fontSize: "1.15rem",
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    color: "#e0f7fa",
  },
  btnHP: {
    padding: "12px 28px",
    background: "transparent",
    border: "1px solid #00f5ff",
    borderRadius: 3,
    color: "#00f5ff",
    fontSize: ".85rem",
    fontWeight: 700,
    cursor: "pointer",
    fontFamily: "'Share Tech Mono', monospace",
    letterSpacing: "0.1em",
    textTransform: "uppercase",
    boxShadow: "0 0 25px rgba(0,245,255,.2),inset 0 0 25px rgba(0,245,255,.05)",
    display: "flex",
    alignItems: "center",
    gap: 8,
    position: "relative",
    overflow: "hidden",
    transition: "all .25s",
  },
  btnHS: {
    padding: "12px 26px",
    background: "rgba(255,255,255,.02)",
    border: "1px solid rgba(255,255,255,.1)",
    borderRadius: 3,
    color: "#e0f7fa",
    fontSize: ".85rem",
    fontWeight: 500,
    cursor: "pointer",
    fontFamily: "'Share Tech Mono', monospace",
    display: "flex",
    alignItems: "center",
    gap: 8,
    letterSpacing: "0.05em",
    transition: "all .25s",
  },
  secLbl: {
    fontFamily: "'Share Tech Mono', monospace",
    fontSize: ".68rem",
    letterSpacing: "4px",
    textTransform: "uppercase",
    color: "#00f5ff",
    marginBottom: 10,
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
  },
  secTitle: {
    fontFamily: "'Orbitron', sans-serif",
    fontSize: "clamp(1.7rem,3.5vw,2.5rem)",
    fontWeight: 900,
    lineHeight: 1.15,
    marginBottom: 14,
    letterSpacing: "-0.02em",
  },
};
